### ISSUE TITLE
Romove duplicated libraries

### ISSUE THREAD

**Issue by alinemati-uwm** [osllmai/indoxJudge#26]
Please remove the duplicated libraries from the project.

dash==2.17.1
dash_bootstrap_components==1.6.0
dash_daq==0.5.0
ipython==8.18.1
ipython==8.12.3
loguru==0.7.2
mistralai==1.0.0
nltk==3.8.1
numpy==2.0.1
pandas==2.0.3
plotly==5.18.0
plotly==5.23.0
protobuf==5.27.3
pydantic==2.8.2
Requests==2.32.3
tenacity==8.2.3
torch==2.3.1
tqdm==4.66.4
transformers==4.39.3

**Comment by AshkanEskandari** [comment]
done 
dash==2.17.1
dash_bootstrap_components==1.6.0
dash_daq==0.5.0
ipython==8.18.1
loguru==0.7.2
nltk==3.8.1
numpy==2.0.1
pandas==2.0.3
plotly==5.23.0
protobuf==5.27.3
pydantic==2.8.2
Requests==2.32.3
tenacity==8.2.3
tqdm==4.66.4
