### ISSUE TITLE
Metrics for mode safety

### ISSUE THREAD

**Issue by alinemati-uwm** [osllmai/indoxJudge#45]
Please let me know if all of below metrics are covered for model safety:

This metics is organized for model safety: 

﻿﻿﻿Toxicity
﻿﻿﻿Stereotype and bias
﻿﻿﻿Adversarial robustness
﻿﻿﻿Out-of-Distribution Robustness
﻿﻿﻿Privacy
﻿﻿﻿Robustness to Adversarial Demonstrations
﻿﻿﻿Machine Ethics
﻿﻿﻿Fairness

Appropriate your time.

**Comment by AshkanEskandari** [comment]
they covered
